src/Entity/CoinCoin.php
<?php

namespace App\Entity;

use AllowDynamicProperties;
use App\Repository\CoinCoinRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[AllowDynamicProperties] #[ORM\Entity(repositoryClass: CoinCoinRepository::class)]

class CoinCoin
{
    public function __construct()
    {
        $this->created_at = new \DateTime();

    }
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $Post = null;

    #[ORM\Column(length: 255)]
    private ?string $Picture = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(length: 50)]
    private ?string $Tags = null;


    #[ORM\ManyToOne(inversedBy: 'coinCoins')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Duck $author = null;

    //GETTER SETTER*****************************************************************************************************
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPost(): ?string
    {
        return $this->Post;
    }

    public function setPost(string $Post): static
    {
        $this->Post = $Post;

        return $this;
    }

    public function getDuckName(): ?string
    {
        return $this->DuckName;
    }

    public function setDuckName(string $DuckName): static
    {
        $this->DuckName = $DuckName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->Picture;
    }

    public function setPicture(string $Picture): static
    {
        $this->Picture = $Picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }


    public function getTags(): ?string
    {
        return $this->Tags;
    }

    public function setTags(string $Tags): static
    {
        $this->Tags = $Tags;

        return $this;
    }

    public function getAuthor(): ?Duck
    {
        return $this->author;
    }

    public function setAuthor(?Duck $author): static
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/CoinCoinType.php
<?php

namespace App\Form;

use App\Entity\CoinCoin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Image;

class CoinCoinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Post')
            ->add('picture', FileType::class,[
            'label' => false,
            'required' => false,
            'mapped' => false,
            'constraints' => [
                new Image([
                    'mimeTypes' => [
                        'image/jpeg',
                        'image/png',
                        'image/gif',
                    ],
                    'mimeTypesMessage' => "Veuillez télécharger une image valide",
                    "maxSize" => '4M',
                    'maxSizeMessage' => "Votre image fait {{size}} {{suffix}}, La limite est de {{ limit }} {{suffix}}"
                ]),
            ]
        ])
            ->add('Tags')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CoinCoin::class,
        ]);
    }
}

src/Controller/CoinCoinController.php
<?php

namespace App\Controller;

use App\Entity\CoinCoin;
use App\Entity\Duck;
use App\Form\CoinCoinType;
use App\Form\CommentType;
use App\Form\DuckType;
use App\Repository\CoinCoinRepository;
use App\Service\UploaderQuackPicture;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/coincoin')]
final class CoinCoinController extends AbstractController
{
    #[Route(name: 'app_coin_coin_index', methods: ['GET'])]
    public function index(CoinCoinRepository $coinCoinRepository): Response
    {
        return $this->render('coin_coin/index.html.twig', [
            'coin_coins' => $coinCoinRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_coin_coin_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SluggerInterface $slugger, UploaderQuackPicture $uploaderQuackPicture,EntityManagerInterface $em): Response
    {
        $user = $this->getUser();

        $product = new CoinCoin();
        $form = $this->createForm(CoinCoinType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $picture = $form->get('picture')->getData();

            if ($picture) {
                $uploadedPicturePath = $uploaderQuackPicture->uploadQuackImage($picture);
                $product->setPicture($uploadedPicturePath);
            }

            $product->setAuthor($user);

            $em->persist($product);
            $em->flush();


            return $this->redirectToRoute('app_coin_coin_index');
        }

        return $this->render('coin_coin/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_coin_coin_show', methods: ['GET'])]
    public function show(CoinCoin $coinCoin): Response
    {
        return $this->render('coin_coin/show.html.twig', [
            'coin_coin' => $coinCoin,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_coin_coin_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CoinCoin $coinCoin, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CoinCoinType::class, $coinCoin);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_coin_coin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('coin_coin/edit.html.twig', [
            'coin_coin' => $coinCoin,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_coin_coin_delete', methods: ['POST'])]
    public function delete(Request $request, CoinCoin $coinCoin, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$coinCoin->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($coinCoin);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_coin_coin_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/coin_coin/_delete_form.html.twig
<form method="post" action="{{ path('app_coin_coin_delete', {'id': coin_coin.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ coin_coin.id) }}">
    <button class="btn">Delete</button>
</form>

templates/coin_coin/_form.html.twig
{% block body %}
{{ form_start(form) }}
    {{ form_widget(form) }}

    <button class="btn btn-warning">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

{% endblock %}

templates/coin_coin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CoinCoin{% endblock %}

{% block body %}
    <h1>Edit CoinCoin</h1>

    {{ include('coin_coin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_coin_coin_index') }}">back to list</a>

    {{ include('coin_coin/_delete_form.html.twig') }}
{% endblock %}

templates/coin_coin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CoinCoin index{% endblock %}

{% block body %}
    <h1>CoinCoin</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Post</th>
                <th>DuckName</th>
                <th>Picture</th>
                <th>Created At</th>
                <th>Tags</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for coin_coin in coin_coins %}
            <tr>
                <td>{{ coin_coin.Post }}</td>
                <td>{{ coin_coin.author.duckName }}</td>
                <td><img src="{{ coin_coin.Picture }}" style="width: 100%"></td>
                <td>{{ coin_coin.createdAt ? coin_coin.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ coin_coin.Tags }}</td>
                <td>
                    {% if is_granted("ROLE_USER","ROLE_ADMIN") %}
                    <button class="btn btn-warning"><a href="{{ path('app_coin_coin_show', {'id': coin_coin.id}) }}">show</a></button>
                    {% endif %}

                        {% if is_granted("ROLE_ADMIN") %}
                        <button class="btn btn-danger"><a href="{{ path('app_coin_coin_edit', {'id': coin_coin.id}) }}">edit</a></button>
                    {% endif %}

                </td>

            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        {% if is_granted("ROLE_USER", "ROLE_ADMIN ") %}
            <button class="btn btn-primary"><a href="{{ path('app_coin_coin_new') }}">Create new</a></button>
        {% endif %}
{% endblock %}

templates/coin_coin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CoinCoin{% endblock %}

{% block body %}
    <h1>Create new CoinCoin</h1>

    {{ include('coin_coin/_form.html.twig') }}

    <button class="btn btn-primary"><a href="{{ path('app_coin_coin_index') }}">back to list</a></button>

{% endblock %}

templates/coin_coin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CoinCoin{% endblock %}

{% block body %}
    <h1>CoinCoin</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ coin_coin.id }}</td>
            </tr>
            <tr>
                <th>Post</th>
                <td>{{ coin_coin.Post }}</td>
            </tr>
            <tr>
                <th>DuckName</th>
{#                <td>{{ coin_coin.DuckName }}</td>#}
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ coin_coin.Picture }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ coin_coin.createdAt ? coin_coin.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Tags</th>
                <td>{{ coin_coin.Tags }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_coin_coin_index') }}">back to list</a>

    <a href="{{ path('app_coin_coin_edit', {'id': coin_coin.id}) }}">edit</a>

    {{ include('coin_coin/_delete_form.html.twig') }}
{% endblock %}